# Generated by Django 4.1.7 on 2023-03-17 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField(default=datetime.datetime(2023, 3, 17, 17, 0, 52, 801789, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
